-- ============================================================
-- 유경원 홈페이지 — 콘텐츠 스키마 + 보안(RLS)
-- Supabase Dashboard → SQL Editor 에 붙여넣고 Run 한 번 실행.
-- 재실행해도 안전하도록 작성(idempotent).
--
-- 보안 원칙:
--   · 공개(anon): 읽기(SELECT)만 허용
--   · 쓰기(INSERT/UPDATE/DELETE): 특정 관리자 uid 만 허용(아래 admin_uid)
--     → 설령 누군가 self-signup 하더라도 관리자 uid가 아니면 쓰기 불가(심층 방어)
--   · 추가로 대시보드 Authentication에서 공개 signup 비활성화 권장.
-- ============================================================

-- 관리자 uid (create-admin.mjs 로 생성된 palujae 계정). 계정을 바꾸면 이 값도 갱신.
-- 참고용 상수: 아래 RLS DO 블록에서 사용.

-- updated_at 자동 갱신 함수
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

-- 공통 컬럼/정책/트리거를 붙이는 헬퍼는 없으므로 테이블마다 반복.
-- 각 테이블: id, sort_order, created_at, updated_at + RLS 2정책 + updated_at 트리거.

-- ---------- profile (단일 행: id = 1) ----------
create table if not exists public.profile (
  id int primary key default 1,
  name_ko text, name_en text, name_hanja text,
  affiliation text, affiliation_en text, title text,
  tagline text, intro jsonb default '[]'::jsonb,
  email text, phone text, office text,
  research_areas jsonb default '[]'::jsonb,
  updated_at timestamptz default now(),
  constraint profile_singleton check (id = 1)
);

-- ---------- education ----------
create table if not exists public.education (
  id bigint generated by default as identity primary key,
  degree text, field text, school text, ym text, note text,
  sort_order int default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- ---------- career (근무경력 + 위원) ----------
create table if not exists public.career (
  id bigint generated by default as identity primary key,
  role text, org text, from_period text, to_period text,
  is_primary boolean default false,
  category text default 'appointment', -- 'employment' | 'appointment'
  sort_order int default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- ---------- publications ----------
create table if not exists public.publications (
  id bigint generated by default as identity primary key,
  title text not null, venue text, ym text,
  type text, topics jsonb default '[]'::jsonb, award text,
  sort_order int default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- ---------- columns (경제 인사이트 / 기고) ----------
create table if not exists public.columns (
  id bigint generated by default as identity primary key,
  title text not null, outlet text, date text, url text,
  sort_order int default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- ---------- media_appearances (언론 인용·인터뷰) ----------
create table if not exists public.media_appearances (
  id bigint generated by default as identity primary key,
  headline text not null, outlet text, reporter text, date text, url text,
  context text, quotes jsonb default '[]'::jsonb, related_topic text,
  sort_order int default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- ---------- videos (방송·영상) ----------
create table if not exists public.videos (
  id bigint generated by default as identity primary key,
  youtube_id text not null, title text, channel text, date text,
  start_seconds int, note text, related_topic text,
  sort_order int default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- ---------- books ----------
create table if not exists public.books (
  id bigint generated by default as identity primary key,
  title text not null, publisher text, date text, note text,
  sort_order int default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- ---------- editorships (학술지 편집) ----------
create table if not exists public.editorships (
  id bigint generated by default as identity primary key,
  role text, journal text, period text,
  sort_order int default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- ---------- policy_activities (정책 자문) ----------
create table if not exists public.policy_activities (
  id bigint generated by default as identity primary key,
  title text not null, role text, org text, date text,
  body jsonb default '[]'::jsonb, quote text,
  source_label text, source_url text,
  sort_order int default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- ============================================================
-- RLS + 트리거 (모든 테이블 동일 패턴)
-- ============================================================
do $$
declare
  t text;
  admin_uid constant text := '1415fdcd-b542-4d85-b906-8b4e528f0db2';
begin
  foreach t in array array[
    'profile','education','career','publications','columns',
    'media_appearances','videos','books','editorships','policy_activities'
  ] loop
    execute format('alter table public.%I enable row level security;', t);

    execute format('drop policy if exists %I on public.%I;', t||'_public_read', t);
    execute format(
      'create policy %I on public.%I for select to anon, authenticated using (true);',
      t||'_public_read', t);

    execute format('drop policy if exists %I on public.%I;', t||'_admin_write', t);
    execute format(
      'create policy %I on public.%I for all to authenticated using (auth.uid() = %L) with check (auth.uid() = %L);',
      t||'_admin_write', t, admin_uid, admin_uid);

    -- updated_at 트리거 (profile 제외한 테이블에도 동일 적용)
    execute format('drop trigger if exists %I on public.%I;', t||'_set_updated_at', t);
    execute format(
      'create trigger %I before update on public.%I for each row execute function public.set_updated_at();',
      t||'_set_updated_at', t);
  end loop;
end $$;
